import type {Metadata} from 'next';
import Image from 'next/image';
import {home} from '../content/home';
import {SiteHeader} from './components/site/SiteHeader';
import {SiteFooter} from './components/site/SiteFooter';
import {CostSection} from './components/site/CostSection';
import {Arrow,JoyArc} from './components/site/Brand';
import './home.css';
import {PartnerStrip} from './components/site/PartnerStrip';
import {Accordion} from './components/site/Accordion';
import {SupportButton,SupportDialog} from './components/site/SupportDialog';
export const metadata:Metadata={title:{absolute:'Tierversicherung für Hund & Katze | PawTrust'},description:'Entdecke Krankenversicherung und OP-Schutz für Hund und Katze. PawTrust erklärt dir, worauf es beim Schutz deines Vierbeiners ankommt.',robots:{index:true,follow:true},alternates:{canonical:'/'},openGraph:{title:'PawTrust – Für euer Leben zusammen.',description:'Krankenversicherung und OP-Schutz für deinen Vierbeiner.',images:['/images/leben-zusammen-hq.webp']}};
function PetLinks(){return <div className="pt-pet-links"><a href={process.env.NEXT_PUBLIC_CALCULATOR_PREVIEW==='1'?'/tarifrechner?tier=hund':'#hund'}><span>Für meinen Hund</span><Arrow/></a><a href={process.env.NEXT_PUBLIC_CALCULATOR_PREVIEW==='1'?'/tarifrechner?tier=katze':'#katze'}><span>Für meine Katze</span><Arrow/></a></div>}
export default function Home(){return <div className="home-page"><SiteHeader/><main id="inhalt">
 <section className="pt-shell pt-hero"><div className="pt-hero-copy"><p className="pt-eyebrow">Tierversicherung für Hund & Katze</p><h1>Für euer Leben<br/><span>zusammen.</span></h1><p className="pt-lead">Du hast die Wahl: OP-Schutz für den Ernstfall oder eine Krankenversicherung, die auch Behandlungen ohne OP abdecken kann. Finde den Schutz, der zu euch passt.</p><PetLinks/><p className="pt-hero-note">Starte mit deinem Hund oder deiner Katze.</p></div><div className="pt-hero-visual"><Image src="/images/leben-zusammen-hq.webp" alt="Eine Frau kuschelt mit ihrem Hund und ihrer Katze auf dem Wohnzimmerteppich" fill priority quality={95} sizes="(max-width: 760px) 100vw, 900px"/><svg className="pt-photo-curve" viewBox="0 0 600 160" aria-hidden="true"><path d="M-20 110 Q120 190 280 95 T630 90" fill="none" stroke="currentColor" strokeWidth="38"/></svg><span>Kleine Momente. Großes Glück.</span></div></section>
 <PartnerStrip/>
 <section className="pt-shell pt-section" id="schutz"><div className="pt-section-heading"><p className="pt-eyebrow">Der passende Schutz beginnt hier</p><h2>Wen möchtest du schützen?</h2><p>Wähle deinen Vierbeiner und entdecke Krankenversicherung und OP-Schutz für euch.</p></div><div className="pt-pet-grid">{home.pets.map(p=><article className="pt-pet-card" id={p.id} key={p.id}><div className="pt-pet-photo"><Image src={p.image} alt={p.name==='Hund'?'Ein fröhlicher Hund auf einem Sofa':'Eine neugierige Katze auf einem Sofa'} fill sizes="(max-width:760px) 90vw, 45vw"/><span>{p.name}</span></div><div className="pt-card-copy"><h3>{p.title}</h3><p>{p.text}</p><div className="pt-card-options"><span>Krankenversicherung</span><span>OP-Schutz</span></div>{process.env.NEXT_PUBLIC_CALCULATOR_PREVIEW==='1'?<a className="pt-button" href={`/tarifrechner?tier=${p.id}`}>Beitrag berechnen <Arrow/></a>:<><button className="pt-button" disabled>Beitrag berechnen <Arrow/></button><small>Online-Abschluss bald verfügbar.</small></>}<a className="pt-text-link" href={p.id==='katze'?'/katzenkrankenversicherung':'#schutzarten'}>{p.id==='katze'?'Katzenkrankenversicherung entdecken':'Schutzarten kennenlernen'} <Arrow/></a></div></article>)}</div></section>
 <section className="pt-brand-section" id="warum-pawtrust"><div className="pt-shell pt-brand-grid"><div><p className="pt-eyebrow">Tierisch nah. Klar im Kopf.</p><h2>Dein Tier ist Familie.<br/>Seine Versicherung sollte verständlich sein.</h2></div><div><JoyArc/><p>Du kennst seinen Lieblingsplatz. Seine kleinen Macken. Und diesen einen Blick.</p><p>Beim Versicherungsschutz sollst du genauso sicher sein: Was ist drin? Was nicht? Und was passt zu euch? Genau dafür gibt es PawTrust.</p></div></div></section>
 <section className="pt-shell pt-section" id="schutzarten"><div className="pt-section-heading"><p className="pt-eyebrow">Zwei Wege, vorzusorgen</p><h2>Welcher Schutz passt zu euch?</h2></div><div className="pt-cover-grid"><article><span className="pt-number">01</span><h3>Für den Fall einer OP.</h3><p>OP-Schutz konzentriert sich auf versicherte Operationen und die damit verbundenen Leistungen.</p><p className="pt-cover-note">Für alle, die besonders größere Operationskosten absichern möchten.</p></article><article><span className="pt-number">02</span><h3>Auch für den Alltag da.</h3><p>Eine Krankenversicherung kann zusätzlich zur OP auch Behandlungen ohne Operation abdecken.</p><p className="pt-cover-note">Für alle, die sich einen umfassenderen Schutz wünschen.</p></article></div><p className="pt-fine">Der konkrete Leistungsumfang richtet sich nach dem gewählten Tarif. Wartezeiten, Selbstbeteiligungen und Ausschlüsse können gelten.</p></section>
 <CostSection/>
 <section className="pt-shell pt-section" id="ablauf"><div className="pt-section-heading"><p className="pt-eyebrow">Einfach Schritt für Schritt</p><h2>Vier Schritte. Ein gutes Gefühl.</h2><p>Von der Tarifwahl bis zur Erstattung – so funktioniert es.</p></div><ol className="pt-steps">{home.steps.map((s,i)=><li key={s.title}><span aria-label={`Schritt ${i+1}`}>{i===3?'✓':i+1}</span><h3>{s.title}</h3><p>{s.text}</p></li>)}</ol><p className="pt-fine">Versicherungsschutz entsteht erst nach wirksamem Vertragsschluss zum vereinbarten Beginn und gemäß den Versicherungsbedingungen.</p></section>
 <section className="pt-shell pt-section pt-faq" id="fragen"><div><p className="pt-eyebrow">Gut gefragt.</p><h2>Damit sich <br/>gut auch <br/>richtig anfühlt.</h2><p>Noch etwas offen?</p><SupportButton/></div><div>{home.faqs.map(f=><Accordion key={f.q} title={f.q}><p>{f.a}</p></Accordion>)}</div></section>
 <section className="pt-shell pt-closing"><JoyArc/><p className="pt-eyebrow">Für alles, was euch verbindet.</p><h2>Viel Liebe. Ein guter Plan.</h2><PetLinks/></section>
 <aside className="pt-shell pt-proof-note" id="tarifhinweis"><p>Die genannten Merkmale beziehen sich auf die entsprechenden Hunde- und Katzentarife von BarmeniaGothaer. Leistungsumfang, Selbstbeteiligung, Wartezeiten und Ausschlüsse richten sich nach dem gewählten Vertrag. Rechnungen werden direkt beim Versicherer eingereicht. Quellen: <a href="https://www.barmeniagothaer.de/hundekranken-versicherung/" target="_blank" rel="noreferrer">Hundekrankenversicherung</a> und <a href="https://www.barmeniagothaer.de/katzenkranken-versicherung/" target="_blank" rel="noreferrer">Katzenkrankenversicherung</a>.</p><p>Stiftung Warentest bewertete den Barmenia-Hunde-OP-Tarif „Premium OP SB 0“ mit „Sehr gut (1,3)“ (Finanzen 05/2025). Das ist keine Bewertung von PawTrust oder anderer Tarife. <a href={home.proof.source} target="_blank" rel="noreferrer">Bewertung beim Versicherer nachlesen ↗</a></p></aside>
 </main><SiteFooter/><SupportDialog/></div>}
