import Link from 'next/link';
import type {Metadata} from 'next';
import Image from 'next/image';
import {SiteHeader} from '../components/site/SiteHeader';
import {SiteFooter} from '../components/site/SiteFooter';
import {CostSection} from '../components/site/CostSection';
import {FeatureIcon} from '../components/site/FeatureIcon';
import {Arrow,JoyArc} from '../components/site/Brand';
import {Accordion} from '../components/site/Accordion';
import {SupportButton,SupportDialog} from '../components/site/SupportDialog';
import {cat} from '../../content/cat';
import '../home.css';
import './product.css';
import {PartnerStrip} from '../components/site/PartnerStrip';
import {ProductActions,MobileQuoteBar} from '../components/site/ProductActions';
import {TariffCards} from '../components/site/TariffCards';
export const metadata:Metadata={title:'Katzenkrankenversicherung – Schutz verstehen',description:'BarmeniaGothaer-Katzentarife verständlich erklärt: Leistungen im Vergleich und ein interaktives Kostenbeispiel bei PawTrust.',alternates:{canonical:'/katzenkrankenversicherung'},openGraph:{title:'Für kleine Pfoten. Und große Pläne. | PawTrust',images:['/images/katze-hero-v2.webp']}};
export default function CatPage(){return <div className="home-page cat-page"><SiteHeader/><main id="inhalt">
<section className="pt-shell pt-hero cat-hero"><div className="pt-hero-copy"><p className="pt-eyebrow">Katzenkrankenversicherung</p><h1>Für kleine Pfoten.<br/>Und große Pläne.</h1><p className="pt-lead">Du kennst ihren Lieblingsplatz. Wir helfen dir, ihren Schutz zu verstehen – für Tierarztbesuche und für den Fall einer OP.</p><ul className="cat-hero-points"><li>Kranken- und OP-Schutz in einem Tarif</li><li>Deine Katze. Deine Tierarztwahl.</li><li>Leistungen und Eigenanteil bewusst wählen</li></ul><ProductActions hero/><a className="pt-text-link cat-tariff-link" href="#tarife">Tarife kennenlernen <Arrow/></a></div><div className="cat-hero-picture"><div className="cat-orbit" aria-hidden="true"/><Image src="/images/katze-hero-v2.webp" alt="Eine entspannte cremefarbene Katze neben der Hand ihres Menschen auf einem hellen Teppich" width={1536} height={1024} priority sizes="(max-width:760px) 95vw, 50vw"/><span className="cat-photo-note"><JoyArc/>Eigenwillig. Einzigartig. Familie.</span></div></section>
<PartnerStrip/>
<section className="pt-shell pt-section"><div className="pt-section-heading"><p className="pt-eyebrow">Für alles zwischen Sofa und Streifzug</p><h2>Weil das Leben nicht<br/>nur auf Samtpfoten kommt.</h2><p>Mal ein ungeplanter Tierarztbesuch, mal eine größere Behandlung. Schau auf den Schutz dahinter – nicht nur auf den Monatsbeitrag.</p></div><div className="cat-benefits">{[{title:'Wenn eine OP nötig wird.',text:'Operation, Diagnostik und Nachbehandlung gehören zusammen. Achte deshalb auch auf die Leistungen vor und nach dem Eingriff.',icon:3},{title:'Wenn es keine OP braucht.',text:'Auch Untersuchungen und Behandlungen ohne Operation können relevant werden. Hier unterscheiden sich die jährlichen Budgets.',icon:0},{title:'Wenn du vorausplanst.',text:'Vorsorge und bestimmte Zahnbehandlungen haben eigene Grenzen. Diese Details machen wir im Vergleich sichtbar.',icon:1}].map(b=><article key={b.title}><FeatureIcon index={b.icon}/><h3>{b.title}</h3><p>{b.text}</p></article>)}</div></section>
<section className="cat-tariffs" id="tarife"><div className="pt-shell"><div className="pt-section-heading"><p className="pt-eyebrow">Dein Blick auf die Tarife</p><h2>Wie viel Schutz<br/>passt zu euch?</h2><p>Drei BarmeniaGothaer-Tarife im Detail. Klar nebeneinander, damit du die Unterschiede siehst.</p></div><TariffCards/><p className="pt-fine">Öffentliche Tarifübersicht, kein persönliches Angebot. Die für PawTrust verfügbare Tarifauswahl wird mit der Vertriebsanbindung bestätigt. Hier gezeigt: reguläre Varianten, keine Akut-Tarife.</p></div></section>
<section className="pt-shell pt-section" id="leistungen"><div className="pt-section-heading"><p className="pt-eyebrow">Die Unterschiede auf einen Blick</p><h2>Weniger Kleingedruckt-Gefühl.<br/>Mehr Überblick.</h2></div><div className="cat-table-scroll" tabIndex={0} role="region" aria-label="Tarifvergleich, seitlich scrollbar"><table className="cat-table"><caption className="cat-sr-only">BarmeniaGothaer Katzenkrankenversicherung: Top, Premium und Premium Plus</caption><thead><tr><th scope="col">Leistung</th>{cat.plans.map(p=><th scope="col" key={p.name}>{p.name}</th>)}</tr></thead><tbody>{cat.rows.map(r=><tr key={r.label}><th scope="row">{r.label}</th>{r.values.map((v,i)=><td key={i}>{v==='Ja'?<span className="cat-check"><span aria-hidden="true">✓</span><span className="cat-sr-only">Enthalten</span></span>:v}</td>)}</tr>)}</tbody></table></div><div className="cat-table-notes"><p>¹ Vorsorge und Zahnbehandlungen werden auf das jährliche Heilbehandlungsbudget angerechnet. Die Akut-Varianten weichen ab. ² Im tariflich definierten tierärztlichen Notdienst.</p><p>Auszug, Stand 24.09.2026. Wartezeiten, Ausschlüsse und weitere Bedingungen gelten. Maßgeblich sind die <Link href={cat.avb} target="_blank" rel="noreferrer">AVB Top / Premium (PDF)</Link> und <Link href={cat.avbPlus} target="_blank" rel="noreferrer">AVB Premium Plus (PDF)</Link>.</p></div><ProductActions/></section>
<section className="pt-brand-section"><div className="pt-shell pt-brand-grid"><div><p className="pt-eyebrow">Tierisch nah. Klar im Kopf.</p><h2>Sie ist nicht einfach<br/>eine Katze.<br/>Sie ist deine Familie.</h2></div><div><JoyArc/><p>Die kleine Nase am Morgen. Das Schnurren auf deinem Schoß. Der Platz auf dem Sofa, der längst ihr gehört.</p><p>Ein guter Plan beginnt damit, zu verstehen, was versichert ist. Und was du selbst übernehmen würdest.</p></div></div></section>
<section className="pt-shell pt-section cat-cost-intro"><div className="pt-section-heading"><p className="pt-eyebrow">Tierarztkosten verstehen</p><h2>Kleine Pfoten.<br/>Manchmal große Rechnungen.</h2><p>Eine Behandlung besteht oft aus mehreren Leistungen. Diese Beispiele zeigen, worauf du beim Schutz für deine Katze achten solltest.</p></div><div className="cat-care-figure"><div className="cat-care-photo"><Image src="/images/katze-kosten-v2.webp" alt="Eine gelassene Katze mit einem kleinen Verband am Vorderbein, illustrative Darstellung" width={1024} height={1024} sizes="(max-width:760px) 90vw, 45vw"/><svg viewBox="0 0 500 500" aria-hidden="true"><path d="M145 165Q100 130 25 110M200 250Q110 260 20 300M350 340Q420 330 480 390"/></svg></div><div className="cat-care-labels"><article><span className="pt-eyebrow">Untersuchung mit Beratung</span><h3>28,11–84,32 €</h3><p>Allgemeine Untersuchung deiner Katze (GOT Nr. 16).</p></article><article><span className="pt-eyebrow">Röntgenaufnahme</span><h3>31,57–94,71 €</h3><p>Je erste oder zweite Aufnahme (GOT Nr. 166).</p></article><article><span className="pt-eyebrow">Injektion</span><h3>13,69–41,06 €</h3><p>Zum Beispiel unter die Haut, ohne das Medikament (GOT Nr. 221).</p></article></div></div><p className="pt-fine">Beispiele einzelner Gebührenpositionen, keine vollständigen Behandlungskosten: 1- bis 3-facher GOT-Satz, inklusive 19 % Umsatzsteuer. Medikamente, Material und weitere Leistungen kommen hinzu; im Notdienst gelten andere Sätze und eine zusätzliche Gebühr. Quelle: <a href="https://www.bundestieraerztekammer.de/tieraerzte/beruf/got/downloads/GOT_allgemein_MerkblattTierhalter2022.pdf" target="_blank" rel="noreferrer">Bundestierärztekammer (PDF)</a>. Unten kannst du eine gesamte Beispielrechnung durchspielen.</p><ProductActions/></section>
<CostSection/>
<section className="pt-shell pt-section pt-faq" id="fragen"><div><p className="pt-eyebrow">Gut gefragt.</p><h2>Für dich klar.<br/>Für sie gut.</h2><p>Du musst nicht alles allein herausfinden.</p><SupportButton label="Kostenlose Beratung"/></div><div>{cat.faqs.map(f=><Accordion key={f.q} title={f.q}><p>{f.a}</p></Accordion>)}</div></section>
<section className="pt-shell pt-closing"><JoyArc/><p className="pt-eyebrow">Für euer Leben zusammen.</p><h2>Viel Schnurren.<br/>Ein guter Plan.</h2><ProductActions/></section>
<aside className="pt-shell pt-proof-note" id="tarifhinweis"><p>Quelle der Tarifangaben: <Link href={cat.source} target="_blank" rel="noreferrer">BarmeniaGothaer Katzenkrankenversicherung</Link> und die oben verlinkten Versicherungsbedingungen. PawTrust ist kein Versicherer. Die Vermittlungs- und Rechneranbindung ist in Vorbereitung; auf dieser Seite werden noch keine Verträge abgeschlossen oder Beratungsanfragen versendet.</p></aside>
</main><MobileQuoteBar/><SiteFooter/><SupportDialog/></div>}
