import { LegalLayout } from '../components/ComingSoon';
export const metadata = { title: 'Datenschutz', robots: { index: false, follow: true } };
export default function Datenschutz() {
  return <LegalLayout title="Datenschutz">
    <p>Diese Hinweise beziehen sich auf die aktuelle PawTrust-Startseite. Stand: September 2026.</p>
    <section><h2>1. Verantwortlicher</h2><p>Marvin Matteo Billig<br />Am Vorgebirgstor 41<br />50969 Köln, Deutschland<br /><a href="mailto:info@pawtrust.de">info@pawtrust.de</a></p></section>
    <section><h2>2. Bereitstellung der Website</h2><p>Unsere Website wird durch Vercel Inc. (USA) bereitgestellt. Beim Aufruf werden technisch erforderliche Verbindungsdaten verarbeitet. Dazu können die IP-Adresse, Zeitpunkt und aufgerufene Adresse, Browser- und Geräteinformationen sowie die zuvor besuchte Seite gehören.</p><p>Die Verarbeitung dient der Auslieferung, Stabilität und Sicherheit der Website. Rechtsgrundlage ist unser berechtigtes Interesse an einem sicheren und funktionsfähigen Internetauftritt gemäß Art. 6 Abs. 1 lit. f DSGVO. Technische Daten werden nur so lange vorgehalten, wie dies für diese Zwecke erforderlich ist; sicherheitsrelevante Ereignisse können eine längere Speicherung erfordern.</p><p>Bei der Bereitstellung können Daten auch in den USA verarbeitet werden. Vercel beschreibt die vertraglichen Schutzmaßnahmen und Standardvertragsklauseln in seinem <a href="https://vercel.com/legal/dpa" rel="noreferrer">Data Processing Addendum</a>. Weitere Informationen: <a href="https://vercel.com/legal/privacy-notice" rel="noreferrer">Datenschutzhinweise von Vercel</a>.</p></section>
    <section><h2>3. Keine Formulare oder Werbetracker</h2><p>Auf dieser Startseite gibt es kein Kontaktformular, keinen Newsletter und keinen Versicherungsrechner. Wir setzen hier keine Analyse- oder Werbetracker ein. Schriften und Bilder werden über die Website selbst ausgeliefert. Social-Media-Inhalte werden nicht eingebettet. Das interaktive Kostenbeispiel rechnet ausschließlich in deinem Browser. Die eingegebenen Beispielwerte werden weder gespeichert noch an uns übermittelt.</p></section>
    <section><h2>4. Kontakt per E-Mail</h2><p>Wenn du uns eine E-Mail schreibst, verarbeiten wir deine E-Mail-Adresse und den Inhalt der Nachricht zur Bearbeitung deiner Anfrage. Die E-Mail-Bereitstellung erfolgt derzeit über IONOS SE, Elgendorfer Straße 57, 56410 Montabaur.</p><p>Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO bei vertragsbezogenen Anfragen, ansonsten Art. 6 Abs. 1 lit. f DSGVO aufgrund unseres Interesses an der Beantwortung von Nachrichten. Wir löschen die Korrespondenz, sobald sie für die Bearbeitung nicht mehr benötigt wird, sofern keine gesetzlichen Aufbewahrungspflichten entgegenstehen.</p></section>
    <section><h2>5. Links zu anderen Websites</h2><p>Links zu externen Quellen führen auf die Website des jeweiligen Anbieters. Erst wenn du einem solchen Link folgst, rufst du die externe Website auf. Dort gelten die Datenschutzhinweise des jeweiligen Anbieters.</p></section>
    <section><h2>6. Deine Rechte</h2><p>Du hast nach Maßgabe der DSGVO das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit. Soweit wir Daten auf Grundlage berechtigter Interessen verarbeiten, kannst du aus Gründen, die sich aus deiner besonderen Situation ergeben, widersprechen (Art. 21 DSGVO). Wende dich dafür an <a href="mailto:info@pawtrust.de">info@pawtrust.de</a>.</p><p>Du kannst dich außerdem bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere am Ort deines gewöhnlichen Aufenthalts, deines Arbeitsplatzes oder des mutmaßlichen Verstoßes. In Nordrhein-Westfalen ist dies die <a href="https://www.ldi.nrw.de/" rel="noreferrer">Landesbeauftragte für Datenschutz und Informationsfreiheit NRW</a>.</p></section>
    {process.env.PAWTRUST_CALCULATOR_PREVIEW==='1'&&<section id="ki-assistent"><h2>7. Optionale KI in der Rechner-Vorschau</h2><p>Enzo verwendet die API von OpenAI. Das Öffnen des Assistenten startet noch keine Übertragung. Erst wenn du ein Gespräch startest oder eine Nachricht sendest, werden Audio beziehungsweise Text und der bisherige Gesprächskontext verarbeitet. Hinzu kommen ausgewählte Angaben aus dem Rechner: Tierart, Name, Geschlecht, Rasse, Gesundheitsangabe, Anzahl weiterer Tiere, Tarifauswahl und aktueller Formularschritt. Das vollständige Geburtsdatum wird nicht als Formularkontext übertragen.</p><p>Der Rechner hält deinen Entwurf im Arbeitsspeicher des geöffneten Browsers. Der lokale Vorschau-Server legt kein dauerhaftes Gesprächsarchiv an. Pause und Minimieren schließen die Sprachverbindung und schalten das Mikrofon ab. Der Tonschalter schaltet nur die Wiedergabe aus. Mit „Gespräch beenden“ wird zusätzlich der sichtbare Gesprächsverlauf zurückgesetzt.</p><p>Nach den API-Datenregeln von OpenAI werden API-Inhalte standardmäßig nicht zum Modelltraining verwendet. Für Missbrauchskontrollen können Inhalte grundsätzlich bis zu 30 Tage aufbewahrt werden; längere Fristen sind unter den dort beschriebenen gesetzlichen und Sicherheitsausnahmen möglich. Einzelheiten stehen in den <a href="https://developers.openai.com/api/docs/guides/your-data" target="_blank" rel="noreferrer">Datenverarbeitungsinformationen von OpenAI</a>. Diese Angaben beschreiben die lokale Testfunktion; ein öffentlicher KI-Abschlussprozess ist noch nicht freigeschaltet.</p></section>}
  </LegalLayout>;
}
