'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useRef,useState} from 'react';
import {Brand} from './Brand';
import {openSupport} from './SupportDialog';
const groups=[{label:'Hund',items:[{label:'Hundekrankenversicherung',href:'/#hund'},{label:'Hunde-OP-Versicherung',href:'/#schutzarten'},{label:'Hundehaftpflichtversicherung',href:''}]},{label:'Katze',items:[{label:'Katzenkrankenversicherung',href:'/katzenkrankenversicherung'},{label:'Katzen-OP-Versicherung',href:'/#schutzarten'}]}];
function Chevron(){return <svg className="pt-chevron" viewBox="0 0 16 16" aria-hidden="true"><path d="m4 6 4 4 4-4" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg>}
export function SiteHeader(){const pathname=usePathname();const dialog=useRef<HTMLDialogElement>(null);const header=useRef<HTMLElement>(null);const toggle=useRef<HTMLButtonElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const [expanded,setExpanded]=useState<string|null>(null);const [closing,setClosing]=useState(false);const [menuOpen,setMenuOpen]=useState(false);
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(!header.current?.contains(e.target as Node))setExpanded(null)};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(dialog.current?.open)toggle.current?.click();else setExpanded(null)}};const resize=()=>{if(innerWidth>1050&&dialog.current?.open){dialog.current.close();setMenuOpen(false);document.body.style.overflow='';setExpanded(null)}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);window.addEventListener('resize',resize);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);window.removeEventListener('resize',resize);if(timer.current)clearTimeout(timer.current);document.body.style.overflow=''}},[]);
 function close(after?:()=>void){if(timer.current)clearTimeout(timer.current);setClosing(true);timer.current=setTimeout(()=>{dialog.current?.close();setMenuOpen(false);document.body.style.overflow='';setClosing(false);setExpanded(null);toggle.current?.focus();after?.()},matchMedia('(prefers-reduced-motion: reduce)').matches?0:220)}
 function nav(mobile:boolean){return <nav aria-label={mobile?'Mobile Hauptnavigation':'Hauptnavigation'} className={mobile?'pt-mobile-links':'pt-desktop-nav'}>{groups.map(g=>{const open=expanded===g.label;const id=`${mobile?'mobile':'desktop'}-${g.label}`;return <div key={g.label} className={`pt-nav-group ${open?'is-open':''}`}><button aria-expanded={open} aria-controls={id} onClick={()=>setExpanded(open?null:g.label)}>{g.label}<Chevron/></button><div id={id} className="pt-nav-dropdown pt-collapse" inert={!open}><div><div className="pt-nav-items">{g.items.map(item=>item.href?<Link key={item.label} href={item.href} onClick={()=>mobile?close():setExpanded(null)}>{item.label}</Link>:<span key={item.label} aria-disabled="true">{item.label}<small>Bald</small></span>)}</div></div></div></div>})}<span className="pt-nav-unavailable" aria-disabled="true">Ratgeber <small>Bald</small></span><Link href="/#warum-pawtrust" onClick={()=>mobile?close():setExpanded(null)}>Über uns</Link><button onClick={()=>mobile?close(openSupport):openSupport()}>Beratung & Support</button></nav>}
 return <header ref={header} className="pt-header"><div className="pt-shell pt-header-inner"><Link href="/" aria-label="PawTrust Startseite"><Brand/></Link>{nav(false)}<Link className="pt-button pt-header-cta" href={process.env.NEXT_PUBLIC_CALCULATOR_PREVIEW==='1'?(pathname==='/katzenkrankenversicherung'?'/tarifrechner?tier=katze':'/tarifrechner'):'/#schutz'}>Beitrag berechnen <span aria-hidden="true">↗</span></Link><button ref={toggle} className={`pt-menu-toggle ${menuOpen&&!closing?'is-active':''}`} aria-label={menuOpen?'Menü schließen':'Menü öffnen'} aria-expanded={menuOpen&&!closing} aria-controls="mobile-menu" onClick={()=>{if(menuOpen){close();return;}setExpanded(null);setClosing(false);setMenuOpen(true);dialog.current?.show();document.body.style.overflow='hidden'}}><span/><span/></button></div>{menuOpen&&<button className="pt-nav-scrim" aria-label="Navigation schließen" tabIndex={-1} onClick={()=>close()}/>}<dialog id="mobile-menu" ref={dialog} className={`pt-menu ${closing?'is-closing':''}`} aria-label="Navigation" onCancel={e=>{e.preventDefault();close()}} onClose={()=>{document.body.style.overflow=''}} onClick={e=>{if(e.target===e.currentTarget)close()}}>{nav(true)}</dialog></header>
}
