'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Brand,JoyArc} from '../components/site/Brand';
import {cat} from '../../content/cat';
import {BreedPicker} from './BreedPicker';
import {EnzoAssistant} from './EnzoAssistant';
import {assistantContext,emptyState,FormState,Pet,Species,Step,steps,validation} from './model';

function Choice({selected,onClick,children}:{selected:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" className={`calc-choice ${selected?'is-selected':''}`} aria-pressed={selected} onClick={onClick}>{children}<span className="calc-radio" aria-hidden="true">{selected?'✓':''}</span></button>}
const titles:Record<Step,string>={species:'Wen möchtest du schützen?',name:'Wie heißt deine Katze?',sex:'Ist deine Katze männlich oder weiblich?',birth:'Wann ist ihr Geburtstag?',breed:'Welche Rasse ist deine Katze?',health:'Gab es schon gesundheitliche Probleme?',others:'Noch mehr Pfoten zu Hause?',plans:'Welcher Schutz passt zu euch?',review:'Dein erster Überblick.'};
export function Calculator(){const query=useSearchParams();const initialSpecies:Species|null=query.get('tier')==='katze'?'cat':query.get('tier')==='hund'?'dog':null;const [state,setState]=useState<FormState>(()=>emptyState(initialSpecies));const [step,setStep]=useState<Step>(initialSpecies?'name':'species');const [error,setError]=useState('');const [saved,setSaved]=useState(false);const titleRef=useRef<HTMLHeadingElement>(null);const mounted=useRef(false);const {pet}=state;const name=pet.name.trim()||(pet.species==='dog'?'dein Hund':'deine Katze');const phase=steps.indexOf(step)<7?0:1;const today=new Date();const maxDate=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
useEffect(()=>{if(mounted.current){titleRef.current?.focus();window.scrollTo({top:0,behavior:'instant'})}mounted.current=true},[step]);
function updatePet(patch:Partial<Pet>){setState(s=>({...s,pet:{...s.pet,...patch}}));setError('');setSaved(false)}
function move(next:Step){setError('');setSaved(false);setStep(next)}
function advance(){const message=validation(step,state);if(message){setError(message);return}if(step==='review'){setSaved(true);return}move(steps[steps.indexOf(step)+1])}
function other(value:string){setState(s=>({...s,otherAnswer:value,extras:value==='yes'?(s.extras.length?s.extras:[{id:crypto.randomUUID(),name:'',species:'cat',breed:''}]):[]}));setError('')}
const title=step==='name'?`Wie heißt ${pet.species==='dog'?'dein Hund':'deine Katze'}?`:step==='sex'?`Ist ${name} männlich oder weiblich?`:step==='birth'?`Wann wurde ${name} geboren?`:step==='breed'?`Welche Rasse ist ${name}?`:step==='health'?`Hatte ${name} schon gesundheitliche Probleme?`:step==='plans'?`Welcher Schutz passt zu ${name}?`:titles[step];
return <div className="home-page calc-page"><header className="calc-header"><Link href="/" aria-label="PawTrust Startseite"><Brand/></Link><span>Dein Schutz. Dein Tempo.</span><Link href={initialSpecies==='cat'?'/katzenkrankenversicherung':'/'} className="calc-exit" aria-label="Rechner verlassen">×</Link></header><main id="inhalt" className={`calc-shell ${step==='plans'?'calc-wide':''}`}><nav className="calc-progress" aria-label="Fortschritt"><ol>{['Dein Tier','Dein Tarif','Deine Daten','Abschluss'].map((label,i)=><li key={label} aria-current={i===phase?'step':undefined} className={i<phase?'is-done':i===phase?'is-current':''}><span><i style={{width:i<phase?'100%':i===phase?`${phase===0?Math.max(12,(steps.indexOf(step)+1)/7*100):step==='review'?100:45}%`:'0%'}}/></span><b>{label}</b></li>)}</ol></nav><div className="calc-meta"><button type="button" className="calc-back" onClick={()=>step==='species'?location.assign('/'):move(steps[steps.indexOf(step)-1])}>← Zurück</button>{pet.species&&<button className="calc-pet-pill" onClick={()=>move('name')} aria-label="Tiernamen bearbeiten">{pet.species==='cat'?<Image src="/images/calculator-cat.png" alt="" width={40} height={40}/>:<span aria-hidden="true">♡</span>}<span>{pet.name.trim()||'Dein Vierbeiner'}</span></button>}</div><section className="calc-question" aria-labelledby="calc-title"><div className="calc-question-heading"><p className="pt-eyebrow">{phase===0?'Wir lernen euch kennen.':'Ein Plan für euch.'}</p><h1 id="calc-title" ref={titleRef} tabIndex={-1}>{title}</h1></div><form onSubmit={e=>{e.preventDefault();advance()}} noValidate>
{step==='species'&&<><p className="calc-intro">Wir starten mit deinem Vierbeiner.</p><div className="calc-species">{([{id:'dog',label:'Hund',src:'/images/hund-wohnen.webp'},{id:'cat',label:'Katze',src:'/images/katze-wohnen.webp'}] as const).map(s=><button key={s.id} type="button" aria-label={s.label} aria-pressed={pet.species===s.id} className={pet.species===s.id?'is-selected':''} onClick={()=>{if(pet.species!==s.id)setState(emptyState(s.id));setError('')}}><Image src={s.src} alt={s.label} width={360} height={260}/><strong>{s.label}</strong><span className="calc-radio">{pet.species===s.id?'✓':''}</span></button>)}</div></>}
{step==='name'&&<><p className="calc-intro">Damit es von Anfang an um euch geht.</p><label className="calc-field" htmlFor="pet-name">Name<input id="pet-name" autoComplete="off" maxLength={40} placeholder={pet.species==='cat'?'Zum Beispiel Luna':'Zum Beispiel Bruno'} value={pet.name} onChange={e=>updatePet({name:e.target.value})}/></label>{pet.name.trim()&&<div className="calc-welcome"><JoyArc/><p><strong>Hallo {pet.name.trim()}.</strong><span>Schön, dass du da bist.</span></p></div>}</>}
{step==='sex'&&<><p className="calc-intro">Eine kleine Angabe zu deinem Vierbeiner.</p><div className="calc-choices"><Choice selected={pet.sex==='male'} onClick={()=>updatePet({sex:'male'})}><span><strong>Männlich</strong><small>{pet.species==='cat'?'Kater':'Rüde'}</small></span></Choice><Choice selected={pet.sex==='female'} onClick={()=>updatePet({sex:'female'})}><span><strong>Weiblich</strong><small>{pet.species==='cat'?'Katze':'Hündin'}</small></span></Choice></div></>}
{step==='birth'&&<><p className="calc-intro">Das Datum findest du meistens im Impfpass.</p><label className="calc-field" htmlFor="pet-birth">{pet.estimated?'Ungefährer Geburtsmonat':'Geburtsdatum'}<input id="pet-birth" type={pet.estimated?'month':'date'} min={pet.estimated?'1990-01':'1990-01-01'} max={pet.estimated?maxDate.slice(0,7):maxDate} value={pet.birth} onChange={e=>updatePet({birth:e.target.value})}/></label><label className="calc-checkbox"><input type="checkbox" checked={pet.estimated} onChange={e=>updatePet({estimated:e.target.checked,birth:''})}/>Ich kenne das genaue Datum nicht.</label>{pet.estimated&&<p className="calc-helper">Monat und Jahr reichen für diesen Entwurf. Vor einem verbindlichen Angebot klären wir das Datum.</p>}</>}
{step==='breed'&&<><p className="calc-intro">Reinrassig, gemischt oder unbekannt – alles hat hier Platz.</p><BreedPicker species={pet.species||'cat'} value={pet.breed} onChange={breed=>updatePet({breed})}/><p className="calc-helper">Du bist dir nicht sicher? Wähle „{pet.species==='dog'?'Mischling':'Hauskatze'} / Rasse unbekannt“.</p></>}
{step==='health'&&<><p className="calc-intro">Gemeint sind bekannte Erkrankungen, Verletzungen oder laufende Behandlungen – auch wenn sie schon länger zurückliegen.</p><div className="calc-choices"><Choice selected={pet.health==='no'} onClick={()=>updatePet({health:'no'})}><span><strong>Nein, keine bekannt</strong></span></Choice><Choice selected={pet.health==='yes'} onClick={()=>updatePet({health:'yes'})}><span><strong>Ja, es gab oder gibt etwas</strong></span></Choice><Choice selected={pet.health==='unsure'} onClick={()=>updatePet({health:'unsure'})}><span><strong>Ich bin unsicher</strong></span></Choice></div><p className="calc-helper">Das hilft, den Schutz richtig einzuordnen. Was versichert werden kann, hängt von den Bedingungen und der Prüfung durch den Versicherer ab.</p>{pet.health&&pet.health!=='no'&&<div className="calc-soft-note">Danke für deine Offenheit. Für diesen ersten Entwurf brauchst du keine Befunde hochzuladen. Die Details klären wir vor einem verbindlichen Angebot.</div>}</>}
{step==='others'&&<><p className="calc-intro">Wenn du möchtest, merken wir weitere Vierbeiner für später vor.</p><div className="calc-choices calc-two"><Choice selected={state.otherAnswer==='yes'} onClick={()=>other('yes')}>Ja</Choice><Choice selected={state.otherAnswer==='no'} onClick={()=>other('no')}>Nein</Choice></div>{state.otherAnswer==='yes'&&<div className="calc-extras">{state.extras.map((extra,index)=><fieldset key={extra.id}><legend>Weiterer Vierbeiner {index+1}</legend><button className="calc-remove" type="button" aria-label={`Tier ${index+1} entfernen`} onClick={()=>setState(s=>({...s,extras:s.extras.filter(p=>p.id!==extra.id)}))}>×</button><label className="calc-field">Name<input value={extra.name} maxLength={40} onChange={e=>setState(s=>({...s,extras:s.extras.map(p=>p.id===extra.id?{...p,name:e.target.value}:p)}))}/></label><label className="calc-field">Tierart<select value={extra.species} onChange={e=>setState(s=>({...s,extras:s.extras.map(p=>p.id===extra.id?{...p,species:e.target.value as Species,breed:''}:p)}))}><option value="cat">Katze</option><option value="dog">Hund</option></select></label><BreedPicker species={extra.species} value={extra.breed} onChange={breed=>setState(s=>({...s,extras:s.extras.map(p=>p.id===extra.id?{...p,breed}:p)}))}/></fieldset>)}{state.extras.length<3&&<button className="calc-text-button" type="button" onClick={()=>setState(s=>({...s,extras:[...s.extras,{id:crypto.randomUUID(),species:'cat',name:'',breed:''}]}))}>+ Weiteres Tier hinzufügen</button>}<p className="calc-helper">Die folgende Tarifauswahl gilt erst einmal für {name}. Weitere Tiere sind hier nur vorgemerkt.</p></div>}</>}
{step==='plans'&&<><p className="calc-intro">Schau zuerst auf die Leistungen. Deinen persönlichen Beitrag ergänzen wir mit der Rechneranbindung.</p>{pet.species==='cat'?<><div className="calc-plans">{cat.plans.map((plan,i)=><article key={plan.name} className={state.plan===plan.name?'is-selected':''}><span className="pt-eyebrow">{plan.intro}</span><h2>{plan.name}</h2><p>{plan.text}</p><dl><div><dt>Heilbehandlungen / Jahr</dt><dd>{i===0?'800 €':state.budget==='unlimited'?'Unbegrenzt':'1.200 €'}</dd></div><div><dt>Operationen</dt><dd>Ohne Jahreslimit</dd></div><div><dt>Nachbehandlung nach OP</dt><dd>{i===2?'120':'30'} Tage</dd></div></dl><button type="button" className={`pt-button ${state.plan===plan.name?'pt-button-primary':'pt-button-secondary'}`} aria-pressed={state.plan===plan.name} onClick={e=>{setState(s=>({...s,plan:plan.name}));setError('');if(innerWidth<=760)e.currentTarget.closest('article')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest',inline:'center'})}}>{state.plan===plan.name?'Ausgewählt ✓':'Tarif auswählen'}</button></article>)}</div>{state.plan&&state.plan!=='Top'&&<label className="calc-field calc-budget">Heilbehandlungsbudget<select value={state.budget} onChange={e=>setState(s=>({...s,budget:e.target.value}))}><option value="1200">1.200 € pro Jahr</option><option value="unlimited">Unbegrenzt</option></select></label>}<p className="calc-helper">Öffentlich dokumentierte Katzentarife von BarmeniaGothaer. Wartezeiten, Ausschlüsse und Selbstbeteiligung gelten je nach Variante. Dieser Entwurf prüft noch keine Annahme und berechnet keinen Preis. <a href={cat.source} target="_blank" rel="noreferrer">Leistungen beim Versicherer</a></p></>:<div className="calc-soft-note">Der Hunde-Einstieg ist vorbereitet. Die Tarifdarstellung bauen wir als Nächstes mit den passenden Hundedaten aus. <button className="calc-text-button" type="button" onClick={()=>{setState(emptyState('cat'));move('name')}}>Katzenablauf ansehen →</button></div>}</>}
{step==='review'&&<><p className="calc-intro">So sieht eure Auswahl bisher aus. Du kannst alles noch ändern.</p><div className="calc-summary"><Image src="/images/calculator-cat.png" alt="" width={80} height={80}/><h2>{name}</h2><dl><div><dt>Geschlecht</dt><dd>{pet.sex==='male'?'Männlich':'Weiblich'}</dd></div><div><dt>Geboren{pet.estimated?' (ungefähr)':''}</dt><dd>{pet.birth}</dd></div><div><dt>Rasse</dt><dd>{pet.breed}</dd></div><div><dt>Tarifentwurf</dt><dd>{state.plan}</dd></div><div><dt>Heilbehandlungen</dt><dd>{state.plan==='Top'?'800 € / Jahr':state.budget==='unlimited'?'Unbegrenzt':'1.200 € / Jahr'}</dd></div><div><dt>Weitere Tiere</dt><dd>{state.extras.length?state.extras.map(p=>p.name).join(', '):'Keine vorgemerkt'}</dd></div></dl><button className="calc-text-button" type="button" onClick={()=>move('name')}>Tierangaben bearbeiten</button><button className="calc-text-button" type="button" onClick={()=>move('plans')}>Tarif ändern</button></div><div className="calc-soft-note">Hier endet der erste Entwurf. Persönliche Daten, verbindlicher Beitrag und Abschluss folgen mit der Versichereranbindung.</div>{saved&&<p role="status" className="calc-soft-note">Deine Auswahl bleibt in dieser geöffneten Vorschau erhalten. Es wurde nichts eingereicht oder abgeschlossen.</p>}</>}
{error&&<p id="calc-error" className="calc-error" role="alert">{error}</p>}<div className="calc-bottom"><button type="submit" className="pt-button pt-button-primary calc-next" disabled={step==='plans'&&pet.species==='dog'} aria-describedby={error?'calc-error':undefined}>{step==='others'?'Zu den Tarifen':step==='plans'?'Auswahl ansehen':step==='review'?'Entwurf merken':'Weiter'}<span aria-hidden="true">→</span></button></div></form></section><p className="calc-preview-note">Entwurf · noch kein verbindliches Angebot</p></main>{pet.species&&<EnzoAssistant context={assistantContext(step,state)}/>}</div>}

