export type Species='cat'|'dog';
export type Pet={species:Species|null;name:string;sex:string;birth:string;estimated:boolean;breed:string;health:string};
export type ExtraPet={id:string;species:Species;name:string;breed:string};
export type FormState={pet:Pet;otherAnswer:string;extras:ExtraPet[];plan:string;budget:string};
export const steps=['species','name','sex','birth','breed','health','others','plans','review'] as const;
export type Step=typeof steps[number];
export const emptyState=(species:Species|null):FormState=>({pet:{species,name:'',sex:'',birth:'',estimated:false,breed:'',health:''},otherAnswer:'',extras:[],plan:'',budget:'1200'});
export const breeds={cat:['Hauskatze / Rasse unbekannt','Europäisch Kurzhaar','Britisch Kurzhaar','Maine Coon','Perser','Ragdoll','Bengal','Siam','Norwegische Waldkatze','Russisch Blau','Sphynx','Mischling','Andere Rasse'],dog:['Mischling / Rasse unbekannt','Labrador Retriever','Golden Retriever','Französische Bulldogge','Deutscher Schäferhund','Dackel','Pudel','Chihuahua','Australian Shepherd','Andere Rasse']};
export function validBirth(value:string,estimated:boolean,now=new Date()){if(!value)return false;const full=estimated?`${value}-01`:value;if(!/^\d{4}-\d{2}-\d{2}$/.test(full))return false;const d=new Date(`${full}T12:00:00`);const today=new Date(now.getFullYear(),now.getMonth(),now.getDate(),23,59,59);return Number.isFinite(d.getTime())&&d.getFullYear()>=1990&&d<=today&&`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`===full;}
export function validation(step:Step,state:FormState):string{const {pet}=state;switch(step){case'species':return pet.species?'':'Wähle Hund oder Katze.';case'name':return pet.name.trim()?'':'Wie heißt dein Tier?';case'sex':return pet.sex?'':'Wähle bitte männlich oder weiblich.';case'birth':return validBirth(pet.birth,pet.estimated)?'':'Bitte gib ein gültiges Datum in der Vergangenheit an.';case'breed':return pet.breed?'':'Wähle eine Rasse oder „Hauskatze / Rasse unbekannt“.';case'health':return pet.health?'':'Wähle eine Antwort. „Ich bin unsicher“ ist auch möglich.';case'others':if(!state.otherAnswer)return 'Wähle Ja oder Nein.';return state.otherAnswer==='yes'&&state.extras.some(p=>!p.name.trim()||!p.breed)?'Ergänze Name und Rasse des weiteren Tiers oder entferne es.':'';case'plans':return state.plan?'':'Wähle einen Tarif für deinen Entwurf.';default:return '';}}
export function assistantContext(step:Step,state:FormState){return {step,animal:state.pet.species==='dog'?'Hund':'Katze',name:state.pet.name,sex:state.pet.sex,ageKnown:!!state.pet.birth,breed:state.pet.breed,health:state.pet.health,additionalPets:state.extras.length,plan:state.plan,budget:state.budget};}
