'use client';
import {useEffect,useRef,useState} from 'react';
import personas from '../../content/assistant-personas.json';
import {ensureAssistantAccess,readVoiceConnection} from './assistantTransport';
export type ChatMessage={role:'user'|'assistant';content:string};
export type EnzoContext={step:string;animal:string;name:string;sex:string;ageKnown:boolean;breed:string;health:string;additionalPets:number;plan:string;budget:string};
type VoiceEvent={type:string;delta?:string;error?:{code?:string}};
export function useEnzoVoice(context:EnzoContext,history:ChatMessage[],onTranscript:(speaker:'user'|'assistant',delta:string,newTurn:boolean)=>void){const [state,setState]=useState<'idle'|'connecting'|'active'|'paused'>('idle');const [status,setStatus]=useState('Bereit, wenn du es bist.');const [muted,setMuted]=useState(false);const [silent,setSilent]=useState(false);const audio=useRef<HTMLAudioElement>(null);const pc=useRef<RTCPeerConnection|null>(null);const dc=useRef<RTCDataChannel|null>(null);const media=useRef<MediaStream|null>(null);const session=useRef<string|null>(null);const generation=useRef(0);const transport=useRef<AbortController|null>(null);const duration=useRef(600);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const latest=useRef({context,history,onTranscript});const speaker=useRef('');const voiceState=useRef(state);
useEffect(()=>{latest.current={context,history,onTranscript}},[context,history,onTranscript]);
function send(event:object){if(dc.current?.readyState==='open')dc.current.send(JSON.stringify({...event,event_id:crypto.randomUUID()}))}
function cleanup(){transport.current?.abort();transport.current=null;if(timer.current)clearTimeout(timer.current);media.current?.getTracks().forEach(t=>t.stop());media.current=null;if(audio.current){audio.current.pause();audio.current.srcObject=null}dc.current?.close();pc.current?.close();dc.current=null;pc.current=null;}
function closeRemote(id:string|null){if(id)void fetch('/api/assistant/close',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id}),keepalive:true}).catch(()=>{})}
function stop(end=false){generation.current++;send({type:'session.close'});closeRemote(session.current);session.current=null;cleanup();voiceState.current=end?'idle':'paused';setState(voiceState.current);setMuted(false);setStatus(end?'Gespräch beendet.':'Gespräch pausiert · Mikrofon aus.');speaker.current=''}
useEffect(()=>{const leave=()=>{generation.current++;if(session.current)navigator.sendBeacon('/api/assistant/close',JSON.stringify({id:session.current}));transport.current?.abort();media.current?.getTracks().forEach(t=>t.stop());dc.current?.close();pc.current?.close();if(timer.current)clearTimeout(timer.current)};window.addEventListener('pagehide',leave);return()=>{window.removeEventListener('pagehide',leave);leave()}},[]);
const contextJson=JSON.stringify(context);
function updateContext(greet=false){if(session.current)void fetch('/api/assistant/context',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:session.current,context:latest.current.context,greet})}).catch(()=>{})}
useEffect(()=>{if(dc.current?.readyState==='open')updateContext()},[contextJson]);
async function start(){if(['active','connecting'].includes(voiceState.current))return;const attempt=++generation.current;voiceState.current='connecting';setState('connecting');setStatus('Verbindung wird vorbereitet …');try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(attempt!==generation.current){stream.getTracks().forEach(t=>t.stop());return}media.current=stream;const peer=new RTCPeerConnection();pc.current=peer;stream.getTracks().forEach(t=>peer.addTrack(t,stream));peer.ontrack=e=>{if(audio.current){audio.current.srcObject=e.streams[0]||new MediaStream([e.track]);void audio.current.play().catch(()=>setStatus('Tippe auf Ton, um Enzo zu hören.'))}};const channel=peer.createDataChannel('oai-events');dc.current=channel;
channel.onmessage=e=>{if(attempt!==generation.current)return;let event:VoiceEvent;try{event=JSON.parse(e.data)}catch{return}if(event.type==='session.started'){if(timer.current)clearTimeout(timer.current);voiceState.current='active';setState('active');setMuted(false);setStatus(`${latest.current.context.animal==='Hund'?personas.dog.name:personas.cat.name} hört zu.`);speaker.current='';updateContext(true);timer.current=setTimeout(()=>stop(),duration.current*1000)}if(event.type==='session.input_transcript.delta'||event.type==='session.output_transcript.delta'){const next=event.type.includes('input_')?'user':'assistant';latest.current.onTranscript(next,event.delta||'',speaker.current!==next);speaker.current=next;setStatus(next==='user'?'Enzo hört zu.':'Enzo antwortet.')}if(event.type==='session.closed'){session.current=null;cleanup();voiceState.current='paused';setState('paused');setStatus('Gespräch pausiert · Mikrofon aus.')}if(event.type==='error'){setStatus('Die Sprachverbindung meldet einen Fehler. Bitte pausiere und starte erneut.')}};
peer.onconnectionstatechange=()=>{if(attempt===generation.current&&['failed','disconnected'].includes(peer.connectionState)){stop();setStatus('Verbindung unterbrochen. Du kannst erneut starten.')}};
await peer.setLocalDescription(await peer.createOffer());if(peer.iceGatheringState!=='complete')await new Promise<void>(resolve=>{const timeout=setTimeout(resolve,3500);peer.addEventListener('icegatheringstatechange',()=>{if(peer.iceGatheringState==='complete'){clearTimeout(timeout);resolve()}})});if(attempt!==generation.current)return;const controller=new AbortController();transport.current=controller;const startup=setTimeout(()=>controller.abort(),35000);let data;try{await ensureAssistantAccess(controller.signal);const response=await fetch('/api/assistant/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sdp:peer.localDescription?.sdp,context:latest.current.context,history:latest.current.history}),signal:controller.signal});data=await readVoiceConnection(response,()=>{if(attempt===generation.current){stop();setStatus('Gespräch pausiert · Du kannst es fortsetzen.')}});}finally{clearTimeout(startup)}if(attempt!==generation.current){closeRemote(data.id);controller.abort();return}duration.current=data.seconds||600;session.current=data.id;await peer.setRemoteDescription({type:'answer',sdp:data.sdp});if(attempt!==generation.current)return;if(voiceState.current==='connecting')timer.current=setTimeout(()=>{if(voiceState.current==='connecting'){stop();setStatus('Verbindung nicht bereit. Bitte erneut starten.')}},20000);
}catch(error){if(attempt!==generation.current)return;closeRemote(session.current);session.current=null;cleanup();voiceState.current='paused';setState('paused');setStatus(error instanceof Error&&error.name==='NotAllowedError'?'Mikrofon nicht freigegeben. Du kannst stattdessen schreiben.':error instanceof Error?error.message:'Verbindung fehlgeschlagen.')}}
function toggleMic(){const next=!muted;setMuted(next);media.current?.getAudioTracks().forEach(t=>t.enabled=!next);send({type:next?'session.input_audio.mute':'session.input_audio.unmute'});setStatus(next?'Mikrofon aus · Enzo kann weiter antworten.':'Enzo hört zu.')}
function toggleSound(){const next=!silent;setSilent(next);if(audio.current){audio.current.muted=next;if(!next)void audio.current.play().catch(()=>{})}}
return {audio,state,status,muted,silent,start,stop,toggleMic,toggleSound};}
